@echo off
echo Stopping containers...
docker stop $(docker ps -q --filter "ancestor=blackjack-app") 2>nul

echo Building application...
mvn clean package -DskipTests

echo Building Docker image...
docker build -t blackjack-app .

echo Starting container...
docker run -p 9000:9000 blackjack-app